### ISSUE TITLE
Deprecated mail sender in RegisterConfirmationModel.

### ISSUE THREAD

**Issue by coderabbits-black** [code-rabbits-team/CodeRabbits.KaoList#72]
The mail sender is not used and the click button is always active.
It should be modified as used in [RegisterConfirmation](https://github.com/dotnet/aspnetcore/blob/v6.0.4/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/RegisterConfirmation.cshtml.cs).

**Comment by coderabbits-red** [comment]
I have modified the value of DisplayConfirmAccountLink to be true as an example.
